### ISSUE TITLE
Text input does not work anymore (RestHopper)

### ISSUE THREAD

**Issue by JosefJoubert** [mcneel/compute.rhino3d#394]
Good day all,

I've been using Rhino Compute for a while now, however I don't update very frequently. I recently updated the server, and it completely broke my program. I narrowed down the problem and will give a possible fix below.

The problem is that 'Text' input no longer works, as it can't be parsed by RestHopper. I mainly use Python to execute Grasshopper scripts on compute, so that is what my minimal example will be of.

My Python script looks like this:
``` python
import compute_rhino3d
import compute_rhino3d.Util
import compute_rhino3d.Grasshopper as gh
import os 
file_directory = os.path.dirname(os.path.realpath(__file__))


# Prepare for communication with RhinoCompute
rhino_URL = "http://localhost:8081/"
compute_rhino3d.Util.url = rhino_URL

GrasshopperScript_filepath = os.path.join(file_directory,"test.gh")

variable_trees = []
Input = "Hello"
# Prepare variables for Grasshopper

variable_tree = gh.DataTree("Text_Input")
variable_tree.Append([0],[Input])
variable_trees.append(variable_tree)
# Execute Grasshopper file
compute_output = gh.EvaluateDefinition(GrasshopperScript_filepath,variable_trees)

print(compute_output)
```

It's just a simple text input. The 'test.gh' is simply:
![image](https://user-images.githubusercontent.com/46576356/124280307-d3a70a00-db48-11eb-9b92-ed71405e4ad2.png)
So it just spits the input back out.

When I run the Python script, I get this error on the server:
```
[15:13:40 ERR] An exception occured while processing request
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at compute.geometry.GrasshopperDefinition.SetInputs(List`1 values) in compute.rhino3d\src\compute.geometry\GrasshopperDefinition.cs:line 339
   at compute.geometry.ResthopperEndpointsModule.GrasshopperSolveHelper(Schema input, String body, Stopwatch stopwatch) in compute.rhino3d\src\compute.geometry\ResthopperEndpoints.cs:line 76
   at compute.geometry.ResthopperEndpointsModule.Grasshopper(NancyContext ctx) in compute.rhino3d\src\compute.geometry\ResthopperEndpoints.cs:line 135
   at compute.geometry.ResthopperEndpointsModule.<.ctor>b__0_0(Object _) in compute.rhino3d\src\compute.geometry\ResthopperEndpoints.cs:line 23
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
::1 - [2021-07-02T15:13:40.7497214+02:00] "POST /grasshopper HTTP/1.1" 500 -
```

In GrasshopperDefinition.cs(330) you have this clause:

``` csharp
case "Text":
        {
            foreach (KeyValuePair<string, List<ResthopperObject>> entree in tree)
            {
                string[] strings = new string[entree.Value.Count];
                for (int i = 0; i < entree.Value.Count; i++)
                {
                    ResthopperObject restobj = entree.Value[i];
                    // Use JsonConvert to properly unescape the string
                    strings[i] = JsonConvert.DeserializeObject<string>(restobj.Data);
                }
                contextualParameter.AssignContextualData(strings);
                break;
            }
        }
        break;
``` 

So the error comes from trying to process the string as a json string, according to the comment it's to unescape the string.

I replaced this clause with:

``` csharp
case "Text":
          {
              foreach (KeyValuePair<string, List<ResthopperObject>> entree in tree)
              {
                  string[] strings = new string[entree.Value.Count];
                  for (int i = 0; i < entree.Value.Count; i++)
                  {
                      ResthopperObject restobj = entree.Value[i];
                      // Use Regex to properly unescape the string
                      strings[i] = Regex.Unescape(restobj.Data);
                  }
                  contextualParameter.AssignContextualData(strings);
                  break;
              }
          }
          break;
```

Using Regex to unescape the string instead of JsonConvert. Now it works for me.

I'm not an expert in Rhino/Grasshopper/Compute, so maybe I'm just doing something wrong. But I hope this was helpful to someone.

**Comment by sbaer** [comment]
Sorry about that. The Regex.Unescape doesn't work for strings representing JSON embedded in the request JSON.

I'm going to go with the following approach for now and see how things work for people.
```
// 2 July 2021 S. Baer (Github issue #394)
// This is pretty hacky and I wish I understood json.net a bit more
// to figure out why it is throwing exceptions in certain cases.
// I'm hoping to support both embedded json inside of other json as
// well as plain strings.
try
{
    // Use JsonConvert to properly unescape the string
    strings[i] = JsonConvert.DeserializeObject<string>(restobj.Data);
}
catch(Exception)
{
    strings[i] = System.Text.RegularExpressions.Regex.Unescape(restobj.Data);
}
```
