### ISSUE TITLE
KeyError thrown in from_input (ghhops_server params.py )

### ISSUE THREAD

**Issue by fstwn** [mcneel/compute.rhino3d#411]
I stumbled upon an error in params.py that I can't really figure out, so I'm posting it here alongside my code. The error message I get is:

`[INFO] Solving using legacy API: <HopsComponent /intri.IntrinsicTriangulation [Mesh -> IntrinsicTriangulation -> IntrinsicTriangulation] >
performed 449 edge flips to Delaunay
[INFO] 127.0.0.1 - - [17/Sep/2021 08:46:15] "POST /solve HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\EFESTWIN\Anaconda3\envs\ddu_ias_research\Lib\site-packages\flask\app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\EFESTWIN\Anaconda3\envs\ddu_ias_research\Lib\site-packages\ghhops_server\middlewares\hopsflask.py", line 43, in __call__
    res, results = self.solve(uri=comp_uri, payload=data)
  File "C:\Users\EFESTWIN\Anaconda3\envs\ddu_ias_research\Lib\site-packages\ghhops_server\base.py", line 53, in solve
    return self._process_solve_request(comp, payload)
  File "C:\Users\EFESTWIN\Anaconda3\envs\ddu_ias_research\Lib\site-packages\ghhops_server\base.py", line 95, in _process_solve_request
    res, inputs = self._prepare_inputs(comp, payload)
  File "C:\Users\EFESTWIN\Anaconda3\envs\ddu_ias_research\Lib\site-packages\ghhops_server\base.py", line 144, in _prepare_inputs
    value = in_param.from_input(in_param_data)
  File "C:\Users\EFESTWIN\Anaconda3\envs\ddu_ias_research\Lib\site-packages\ghhops_server\params.py", line 186, in from_input
    for param_value_item in input_data["InnerTree"]["0"]:
KeyError: '0'`

My code that is apparently causing this is as follows:
`@hops.component(
    "/intri.IntrinsicTriangulation",
    name="IntrinsicTriangulation",
    nickname="InTri",
    description="Compute intrinsic triangulation of a triangle mesh.",
    category=None,
    subcategory=None,
    icon=None,
    inputs=[
        hs.HopsMesh("Mesh", "M", "The triangle mesh to create intrinsic triangulation for.", hs.HopsParamAccess.ITEM), # NOQA501
    ],
    outputs=[
        hs.HopsMesh("IntrinsicTriangulation", "T", "The resulting Mesh with an intrinsic triangulation.", hs.HopsParamAccess.ITEM), # NOQA501
    ])
def intri_IntrinsicTriangulationComponent(mesh):

    # get vertices and faces as numpy arrays
    V, F = hsutil.rhino_mesh_to_np_arrays(mesh)

    # initialize the glue map and edge lengths arrays from the input data
    G = intri.build_gluing_map(F)
    eL = intri.build_edge_lengths(V, F)

    # flip to delaunay
    intri.flip_to_delaunay(F, G, eL)

    # duplicate original mesh and clear the faces
    intri_mesh = mesh.Duplicate()
    intri_mesh.Faces.Clear()

    # set the intrinsic traignulation as faces
    [intri_mesh.Faces.AddFace(face[0], face[1], face[2]) for face in F]

    # compute normals and compact
    intri_mesh.UnifyNormals()
    intri_mesh.Normals.ComputeNormals()
    intri_mesh.Compact()

    # return results
    return intri_mesh`

The interesting thing is that the component still solves and is returning the correct results ?!
I'm running Hops using rhinoinside. Hope this helps, I'll gladly provide more info if needed.

Best,
Max

**Comment by fengqingthu** [comment]
Seen this as well! Someone can help?

**Comment by MaxBromberg** [comment]
Hello!
I've found the same error, which as far as I can tell is simply from an typo in manually indexing the "{0}".

I mentioned this in the [forms](https://discourse.mcneel.com/t/error-error-on-request-running-cpython-through-hops-flask/156897/3) but the solution has yet to be patched in as of now (1.5.5 ghhops-server release)

In line 210 of `...\venv\lib\site-packages\ghhops_server\params.py`, remove the curl brackets around 0:
`for param_value_item in input_data["InnerTree"]["{0}"]:` --> `for param_value_item in input_data["InnerTree"]["0"]:`

Oh; I just had another look at the original post, which seems to have the '_corrected_' version already, though my 'edit' is still seemingly relevant (at least for me) now with the latest release... 

**Update**: This is a python-version dependent issue; if python 3.10 is used, the error occurs (and requires the fix above) but for python 3.8 (and `ghhops-server==1.5.5`) this is not an issue.
