### ISSUE TITLE
Error when trying to install ghhops for CPython hops componenet development

### ISSUE THREAD

**Issue by karim-daw** [mcneel/compute.rhino3d#597]
Hello, 

I was trying to get started with a CPython component using Hops and wehn following the very first step to pip install the ghhops_server i throws this error:

```
(env) PS C:\Users\43310\source\repos\hops-data-management> pip install ghhops_server==1.5.5
Collecting ghhops_server==1.5.5
  Using cached ghhops_server-1.5.5-py2.py3-none-any.whl (11 kB)
Collecting rhino3dm
  Using cached rhino3dm-7.14.2.tar.gz (5.7 MB)
  Preparing metadata (setup.py) ... done
Installing collected packages: rhino3dm, ghhops_server
  DEPRECATION: rhino3dm is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package 
is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for rhino3dm ... error
  error: subprocess-exited-with-error

  × Running setup.py install for rhino3dm did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      running install
      C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\rhino3dm
      copying src\rhino3dm\__init__.py -> build\lib.win-amd64-cpython-311\rhino3dm
      running egg_info
      writing src\rhino3dm.egg-info\PKG-INFO
      writing dependency_links to src\rhino3dm.egg-info\dependency_links.txt
      writing top-level names to src\rhino3dm.egg-info\top_level.txt
      reading manifest file 'src\rhino3dm.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pyd' under directory 'src\rhino3dm'
      warning: no files found matching '*.so' under directory 'src\rhino3dm'
      adding license file 'LICENSE'
      writing manifest file 'src\rhino3dm.egg-info\SOURCES.txt'
      copying src\rhino3dm\__init__.pyi -> build\lib.win-amd64-cpython-311\rhino3dm
      copying src\rhino3dm\py.typed -> build\lib.win-amd64-cpython-311\rhino3dm
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\43310\AppData\Local\Temp\pip-install-jmeobntr\rhino3dm_e03d81a0cb894fcc874f064efc88b8a2\setup.py", line 32, in run
          out = subprocess.check_output(['cmake', '--version'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\43310\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\43310\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\43310\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\43310\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\43310\AppData\Local\Temp\pip-install-jmeobntr\rhino3dm_e03d81a0cb894fcc874f064efc88b8a2\setup.py", line 111, in <module>
          setup(
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\43310\source\repos\hops-data-management\env\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\43310\AppData\Local\Temp\pip-install-jmeobntr\rhino3dm_e03d81a0cb894fcc874f064efc88b8a2\setup.py", line 34, in run
          raise RuntimeError(
      RuntimeError: CMake must be installed to build the following extensions: rhino3dm._rhino3dm
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> rhino3dm

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by karim-daw** [comment]
Update: I see this issue was brought up and its due to using Python 3.11, the solution by Steve was to donwgrade to 3.10:

[https://discourse.mcneel.com/t/problems-with-hops-and-ghhops-server/153276](url)

cheers
